#!/bin/bash -x

NAZWA_PROGRAMU="Detective Windows 0.3"
IKONA=~/DW/main/graf/DooFi_detective64.png
PLIK_LICENCJA="gpl-3.0.txt"

function log()
{
	echo $1 >> ${KATALOG_GLOWNY}/log.txt 
}

function zamontuj_partycje()
{
	
}

DATA=`date "+%y-%m-%d %H:%M:%S"`

#gui startowe - akceptacja warunkow licencji 
zenity --text-info --title="Detective Windows" --filename=$PLIK_LICENCJA --html --checkbox="I read and accept the terms."

case $? in
    0)
        log "$DATA - Accept licence and start program"
	;;
    1)
        log "$DATA - NOT accept licences and stop program"
	exit
	;;
    -1)
        echo "$DATA - An unexpected error has occurred during start program"
	exit
	;;
esac

zamontuj_partycje

#gui - podaj nazwe badania
NAZWA_SPRAWY=$(yad --title="$NAZWA_PROGRAMU" --image=$IKONA --text="<b>  Insert name of case</b>" --form --field="Name of case" "First case")

#gdy pole jest puste to koniec programu
[ "$NAZWA_SPRAWY" == "" ] && exit

#usowamy separator |
NAZWA_SPRAWY=$(echo $NAZWA_SPRAWY | tr -d "|" )

#zamieniamy spacje na podkreslenia
NAZWA_SPRAWY=$(echo $NAZWA_SPRAWY | tr " " "_")

#data w formacie UTC czyli liczba sekund od 1.1.1970
CZAS_OBECNY=$(date +%s)

#katalog w ktorym beda zapisane wszystkie wyniki z badania systemu
KATALOG_SPRAWY=${NAZWA_SPRAWY}_${CZAS_OBECNY}

#gui - podaj na jakim nosniku/katalogu zapisac badanie
MIEJSCE_ZAPISU=$(yad --file --directory --title="$NAZWA_PROGRAMU" --image=$IKONA --text="<b>  Where to save result ?</b>" --height=380)

#gdy pole jest puste to koniec programu
[ "$MIEJSCE_ZAPISU" == "" ] && exit




