#!/bin/bash -x

#format wywolania pliku: skopiuj_komunikatory uzytkownik klomunikator. Przyklad: skopiuj_komunikatory admin WLM
#kopiuje poczte z zapisanych sciezek w katalogu poczty

KATALOG_GLOWNY=~/DW/badanie

function log()
{
	echo $1 >> ${KATALOG_GLOWNY}/log.txt 
}

UZYTKOWNIK=$1
KOMUNIKATOR=$2

KATALOG_PRZEZNACZENIA=${KATALOG_GLOWNY}/Users/${UZYTKOWNIK}/Communicators/${KOMUNIKATOR} 

DATA=`date "+%y-%m-%d %H:%M:%S"`

log "$DATA - Preapering to copy ${KOMUNIKATOR} archives files."

if [ ! -d $KATALOG_PRZEZNACZENIA ]; then 
	log "-  Error with copy. No ${KATALOG_PRZEZNACZENIA} folder."
	exit 1; #koniec skryptu
elif [ ! -e $KATALOG_PRZEZNACZENIA/path_${KOMUNIKATOR}_archives.txt ]; then
	log "-  Error with copy. No path_${KOMUNIKATOR}_archives.txt file."
	exit 1; #koniec skryptu
elif [ ! -s $KATALOG_PRZEZNACZENIA/path_${KOMUNIKATOR}_contacts.txt ]; then
	log "-  Error with copy. File path_${KOMUNIKATOR}_archives.txt is empty."
	exit 1; #koniec skryptu
else
	while read SCIEZKA_DO_ORYGINALU
	do
		#kopiuje wszystkie pliki,katalogi i podkatalogi
		cp -R "$SCIEZKA_DO_ORYGINALU"  "$KATALOG_PRZEZNACZENIA" &&
			#jesli sie uda skopiowac
			log "-  Coped ${KOMUNIKATOR} files. OK." ||
				#jesli sie nie uda
				log "-  Error with copy ${KOMUNIKATOR} files. Error."
	done < $KATALOG_PRZEZNACZENIA/path_${KOMUNIKATOR}_archives.txt
fi
