#!/bin/bash -x

#format wywolania pliku: skopiuj_poczte uzytkownik klient poczty. Przyklad: skopiuj_poczte admin WLM
#kopiuje poczte z zapisanych sciezek w katalogu poczty

KATALOG_GLOWNY=~/DW/badanie

function log()
{
	echo $1 >> ${KATALOG_GLOWNY}/log.txt 
}

UZYTKOWNIK=$1
KLIENT_POCZTY=$2

SCIEZKA_DO_KATALOGU_KLIENTA=${KATALOG_GLOWNY}/Users/${UZYTKOWNIK}/Mail/${KLIENT_POCZTY} 

DATA=`date "+%y-%m-%d %H:%M:%S"`

log "$DATA - Preapering to copy ${KLIENT_POCZTY} files."

if [ ! -d $SCIEZKA_DO_KATALOGU_KLIENTA ]; then 
	log "-  Error with copy. No ${SCIEZKA_DO_KATALOGU_KLIENTA} folder."
	exit 1; #koniec skryptu
elif [ ! -e $SCIEZKA_DO_KATALOGU_KLIENTA/path_${KLIENT_POCZTY}.txt ]; then
	log "-  Error with copy. No path_${KLIENT_POCZTY}.txt file."
	exit 1; #koniec skryptu
elif [ ! -s $SCIEZKA_DO_KATALOGU_KLIENTA/path_${KLIENT_POCZTY}.txt ]; then
	log "-  Error with copy. File path_${KLIENT_POCZTY}.txt is empty."
	exit 1; #koniec skryptu
else
	while read $SCIEZKA_DO_ORYGINALU
	do
        	#kopiuje wszystkie pliki,katalogi i podkatalogi
		cp -R "$SCIEZKA_DO_ORYGINALU"  "$SCIEZKA_DO_KATALOGU_KLIENTA" &&
			#jesli sie uda skopiowac
			log "-  Coped ${KLIENT_POCZTY} files. OK." ||
				#jesli sie nie uda
				log "-  Error with copy ${KLIENT_POCZTY} files. Error." 
	done < $SCIEZKA_DO_KATALOGU_KLIENTA/path_${KLIENT_POCZTY}.txt
fi


