#!/bin/bash -x

#format wywolania pliku: wyszukaj_PPZEGLADARKA uzytkownik PPZEGLADARKA. Przyklad: WYSZUKAJ_pRZEGLADARKI admin Ie
#kopiuje poczte z zapisanych sciezek w katalogu poczty

KATALOG_GLOWNY=~/DW/badanie

function log()
{
	echo $1 >> ${KATALOG_GLOWNY}/log.txt 
}

UZYTKOWNIK=$1
PPZEGLADARKA=$2

DATA=`date "+%y-%m-%d %H:%M:%S"`

log "$DATA - I look for ${PPZEGLADARKA} archives."

#tworzy katalogi jesli niema
mkdir -p "${KATALOG_GLOWNY}/Users/${UZYTKOWNIK}/Browsers/${PPZEGLADARKA}" &&
log "- ${PPZEGLADARKA} folders on destination drive correct. OK" || 
{ log " I coud NOT create ${PPZEGLADARKA} folders on destination drive. Error."; exit 1; }

if [ $PPZEGLADARKA == "IE" ]; 
then
	for PARTYCJA in `cat ${KATALOG_GLOWNY}/system_info/partycja_systemowa_windows.txt`
   	    do
		find /media/${PARTYCJA}/Users/${UZYTKOWNIK}/AppData/Local/Microsoft/Windows/Temporary\ Internet\ Files -name "index.dat" > ${KATALOG_GLOWNY}/Users/${UZYTKOWNIK}/Browsers/${PPZEGLADARKA}/path_${PPZEGLADARKA}_archives.txt && log  "- Link to ${PPZEGLADARKA} archive saved correct. OK." || log "- I could not find ${PPZEGLADARKA} archives on ${PARTYCJA}"		
	done
elif [ $PPZEGLADARKA == "Firefox" ]; 
then
	for PARTYCJA in `cat ${KATALOG_GLOWNY}/system_info/partycja_systemowa_windows.txt`
   	    do
		find /media/${PARTYCJA}/Users/${UZYTKOWNIK}/AppData/Roaming/Mozilla/Firefox/Profiles -type f -iname "formhistory.sqlite" -o -iname "downloads.sqlite" -o -iname "cookies.sqlite" -o -iname "places.sqlite"> ${KATALOG_GLOWNY}/Users/${UZYTKOWNIK}/Browsers/${PPZEGLADARKA}/path_${PPZEGLADARKA}_archives.txt 
		ILOSC_ZNALEZIONYCH=`cat ${KATALOG_GLOWNY}/Users/${UZYTKOWNIK}/Browsers/${PPZEGLADARKA}/path_${PPZEGLADARKA}_archives.txt | wc -l`			
		[ "$ILOSC_ZNALEZIONYCH" == 4 ] && log  "- Link to ${ILOSC_ZNALEZIONYCH} ${PPZEGLADARKA} archives saved correct. OK." || log "- I could not find all ${PPZEGLADARKA} archives on ${PARTYCJA}. I found only ${ILOSC_ZNALEZIONYCH} archives"	
	done
elif [ $PPZEGLADARKA == "Chrome" ]; 
then
	for PARTYCJA in `cat ${KATALOG_GLOWNY}/system_info/partycja_systemowa_windows.txt`
   	    do
		find /media/${PARTYCJA}/Users/${UZYTKOWNIK}/AppData/Local/Google/Chrome -type f -iname "Bookmarks" -o -iname "Cookies" -o -iname "History" -o -iname "Login Data" -o -iname "Web Data"> ${KATALOG_GLOWNY}/Users/${UZYTKOWNIK}/Browsers/${PPZEGLADARKA}/path_${PPZEGLADARKA}_archives.txt 	
		#zlicza ilosc znalezionych i zapisanych archiwow		
		ILOSC_ZNALEZIONYCH=`cat ${KATALOG_GLOWNY}/Users/${UZYTKOWNIK}/Browsers/${PPZEGLADARKA}/path_${PPZEGLADARKA}_archives.txt | wc -l`			
		[ "$ILOSC_ZNALEZIONYCH" == 5 ] && log  "- Link to ${ILOSC_ZNALEZIONYCH} ${PPZEGLADARKA} archives saved correct. OK." || log "- I could not find all ${PPZEGLADARKA} archives on ${PARTYCJA}. I found only ${ILOSC_ZNALEZIONYCH} archives"
	done
fi
