#!/bin/bash -x

KATALOG_GLOWNY=~/DW/badanie

#wyszukuje poczte WLM na kazdym koncie uzytkownika
for PARTYCJA in `cat ${KATALOG_GLOWNY}/system_info/partycje_win.txt`
   do

	for UZYTKOWNIK in `cat ${KATALOG_GLOWNY}/system_info/uzytkownicy_systemu.txt`
   	   do

		#tworzy katalogi jesli nie ma
		if [ ! -d ${KATALOG_GLOWNY}/Users/${UZYTKOWNIK} ]; then 
			mkdir ${KATALOG_GLOWNY}/Users/${UZYTKOWNIK}; fi
		if [ ! -d ${KATALOG_GLOWNY}/Users/${UZYTKOWNIK}/Mail ]; then 
			mkdir ${KATALOG_GLOWNY}/Users/${UZYTKOWNIK}/Mail; fi
		if [ ! -d ${KATALOG_GLOWNY}/Users/${UZYTKOWNIK}/Mail/Thunderbird; then 
			mkdir ${KATALOG_GLOWNY}/Users/${UZYTKOWNIK}/Mail/Thunderbird; fi

		DATA=`date "+%y-%m-%d %H:%M:%S"`

		#zapisuje loga
		echo $DATA "- I am looking for Thunderbird folder on ${PARTYCJA}..." >> ${KATALOG_GLOWNY}/log.txt

		SCIEZKA_DO_THUNDERBIRD="/media/${PARTYCJA}/Users/${UZYTKOWNIK}/AppData/Roaming/Thunderbird"
		if [ -d  "$SCIEZKA_DO_THUNDERBIRD" ]
		  then
			#zapisuje sciezke do WLM
			echo $SCIEZKA_DO_THUNDERBIRD > ${KATALOG_GLOWNY}/Users/${UZYTKOWNIK}/Mail/Thunderbird/path_Thunderbird.txt
			#zapisuje loga
			echo "  I found Thunderbird folder in ${SCIEZKA_DO_THUNDERBIRD}" >> ${KATALOG_GLOWNY}/log.txt
			#szukamy zalozonych kont
			find "${SCIEZKA_DO_THUNDERBIRD}" -iname "*.eml" > ${KATALOG_GLOWNY}/Users/${UZYTKOWNIK}/Mail/Thunderbird/mails_in_Thunderbird.txt
			#zlicza ilosc znalezionych maili
			ILOSC_MAILI=$(cat ${KATALOG_GLOWNY}/Users/${UZYTKOWNIK}/Mail/Thunderbird/mails_in_Thunderbird.txt | wc -l )
			echo "  I found ${ILOSC_MAILI} counts in Thunderbird" >> ${KATALOG_GLOWNY}/log.txt
 		  else 
			#zapisuje loga
			echo "  I did not find Thunderbird folder in ${SCIEZKA_DO_THUNDERBIRD}" >> ${KATALOG_GLOWNY}/log.txt
		fi

	done 

done
