#!/bin/bash -x

#skrypt wyszukuje i montuje partycje windosowe

KATALOG_GLOWNY=~/DW/badanie

function log()
{
	echo $1 >> $KATALOG_GLOWNY/log.txt
}

function sprawdz_czy_dysk_zamontowany() 
{
    if [ -n "$(grep $1 /proc/mounts)" ]
    then
  	log "- Checking- Partition /dev/${1} mounted already"
        return 1 #zamontowany
    else
	log "- Checking- Partition /dev/${1} not mounted"
        return 0 #nie zamontowany
    fi 
}

function montujemy() 
{
  # zmienna $1 przejmuje wartosc argumentu wywolania np. sda1
  # mountujemy w trybie do odczytu -r
  sudo mount -r /dev/"$1" /media/"$1" 
  log "- Partition /dev/${1} mounted in /media/${1}"
	
}

DATA=`date "+%y-%m-%d %H:%M:%S"`

log "$DATA - Prapere to find disk with windows partitions"

#wyszukuje wszystkie dyski i partycje
sudo fdisk -l | 
#wyszykuje tylko te windosowe i zapisuje do pliku
grep 'HPFS\|NTFS\|exFAT\|FAT' |
#pobiera pierwsza kolumne i zapisuje do pliku
awk '{ print $1 }' | 
#zapisuje pelna sciezke do dyskow
tee ${KATALOG_GLOWNY}/system_info/partycje_win_fullpath.txt |
#oraz selekcjonuje np. z /dev/sda1 drugi czlon - sda1 i zapisuje
cut -d / -f 3 > ${KATALOG_GLOWNY}/system_info/partycje_win.txt


#jesli plik istnieje lub nie jest pusty
if [ -e ${KATALOG_GLOWNY}/system_info/partycje_win.txt ] && [ -s ${KATALOG_GLOWNY}/system_info/partycje_win.txt ]
then
	ILOSC_PARTYCJI=`cat ${KATALOG_GLOWNY}/system_info/partycje_win.txt | wc -l`
	log "- Found ${ILOSC_PARTYCJI} windows partition/s"
	#yad --title="$NAZWA_PROGRAMU" --text="I look for disks and partitions" --timeout=5 --no-buttons
else
	log "- No file with info about windows partition or file is empty"
	exit 1
fi 


#pobiera z pliku nazwy partycji do zamontowania
for PARTYCJA_DO_ZAMONTOWANIA in `cat ${KATALOG_GLOWNY}/system_info/partycje_win.txt`
do
	sprawdz_czy_dysk_zamontowany "$PARTYCJA_DO_ZAMONTOWANIA"
	if [ $? == 0 ] # nie zamontowana
	then
    		#sprawdzamy czy katalog juz istnieje
		#jesli istnieje montujemy 
		if [ -d /media/${PARTYCJA_DO_ZAMONTOWANIA} ]; then 
			montujemy ${PARTYCJA_DO_ZAMONTOWANIA}
		else 
			#jesli nie istnieje tworzymy go
			sudo mkdir /media/${PARTYCJA_DO_ZAMONTOWANIA} 
			#i montujemy
			montujemy ${PARTYCJA_DO_ZAMONTOWANIA}
		fi	
	fi
done





